### ISSUE TITLE
can´t start slideshow?!

### ISSUE THREAD

**Issue by mmuncan** [GitMirar/shodan-slideshow#1]
Hello,
i installed and everything is on the server now and then this is what comes back:

root@XXX:~/h4ck/shodan-slideshow# ./slideshow -dumpdir /root/h4ck/shodan-slideshow/ -logfile slideshow.log
panic: could not read error response

goroutine 1 [running]:
log.Panic(0xc0000b9f18, 0x1, 0x1)
        /usr/lib/go/src/log/log.go:351 +0xae
main.main()
        /root/h4ck/shodan-slideshow/slideshow.go:95 +0x319

what do i have to do to make it running? :)

**Comment by GitMirar** [comment]
I could not reproduce the crash but it may very well be that stuff is broken, the vnc library for example has not been updated for some years ... archiving this project
